### ISSUE TITLE
No results found for "clippy". 3 results found outside diff.

### ISSUE THREAD

**Issue by jyn514** [giraffate/clippy-action#36]
I'm not sure if this is actually a bug, but I didn't see a chat platform for this repo. I'm trying to add this action to cargo-sweep and I'm not seeing CI fail or annotations being generated, even though clippy shows warnings locally: https://github.com/holmgr/cargo-sweep/actions/runs/3773852477/jobs/6415601213#step:5:30
```
  reviewdog: Reporting results for "clippy"
  reviewdog: No results found for "clippy". 3 results found outside diff.
```
Do you know what could be going wrong here? There's a warning above that GITHUB_TOKEN is missing permissions but I wouldn't expect that to be related. "3 results found outside diff" makes me think the warnings are being generated but filtered out, or something like that?

**Comment by giraffate** [comment]
> "3 results found outside diff" makes me think the warnings are being generated but filtered out, or something like that?

I think so. This action uses reviewdog and reviewdog has some [filter modes](https://github.com/reviewdog/reviewdog#filter-mode). The `added` mode is default and filter results by added/modified lines. The `nofilter` mode is also available if we don't use any filter. In this action, we can set it by `filter_mode`.

**Comment by jyn514** [comment]
Got it, thank you!
